### ISSUE TITLE
Issue about CRAFT corpus.

### ISSUE THREAD

**Issue by Eulring** [hu-ner/huner#10]
We are making a comparison with huner on CRAFT in our new research. 
Could you please provide the processed CRAFT corpus or processing details, cause the results of our experiments are inconsistent with which on the paper.

**Comment by yetinam** [comment]
Hey,
thank you for your interest in the HUNER corpora. We updated the repository with the scripts for CRAFT (1628fca9049927d4cdf358fabfaa3cc662b268e5). For obtaining the processed CRAFT corpus, please apply the following steps:
- Download the corpus from http://sourceforge.net/projects/bionlp-corpora/files/CRAFT/v2.0/craft-2.0.tar.gz/download
- Convert the corpus using `OPENNLP=/path/to/opennlp convert_craft.sh CRAFTPATH`

Please let us know, if you encounter further problems.

**Comment by Eulring** [comment]
Thanks, yetinam, in our new experiments, we have obtained close results. We appreciate your reply and word on huner.

**Comment by Eulring** [comment]
The processed craft.conll file only has one sentence, I wonder if it is a '\n' missed between each sentence?

**Comment by Eulring** [comment]
The error might lie on the command "awk '{print $2"\t"$3"\t"$4}' craft_chemicals_tmp.conll > craft_chemicals.conll"

**Comment by yetinam** [comment]
Hey,
thanks for bringing this to our attention. Indeed, the awk command was slightly off. Should be fixed in 4e3e024.
