### ISSUE TITLE
Query regarding datasets

### ISSUE THREAD

**Issue by nakumgaurav** [hu-ner/huner#12]
Hi, 
For my project, I am required to extract all the entities in all the datasets that HUNER uses for training. I saw that many of the datasets have train/test splits. Have you used the entire dataset to train HUNER models or only the train part of the datasets?

**Comment by yetinam** [comment]
Hey @nakumgaurav ,
HUNER splits every corpus into train/dev/test. HUNER is trained only on the train parts of each Corpus.

**Comment by nakumgaurav** [comment]
Thanks a lot!
