### ISSUE TITLE
How to train a Huner model from scratch on other datasets?

### ISSUE THREAD

**Issue by Eulring** [hu-ner/huner#13]

**Comment by leonweber** [comment]
Hey @Eulring , thanks for your interest in using HUNER. I have added training scripts to the repository and updated the README with instructions for training. Please let us know if that resolves your issue.

**Comment by Eulring** [comment]
Thanks @leonweber, But we still encounter an error in current scripts: 
    'Exception: CoNLL evaluation script not found at "./evaluation/conlleval"'

**Comment by leonweber** [comment]
Hey @Eulring, thanks for reporting back. On a freshly checked out version of the repository, this works for me:

```bash
 ./train_no_finetune.sh data/osiris.conll.train data/osiris.conll.dev data/osiris.conll.test
```

On the following commit:

```bash
commit edaed5766860f3b5aca2e97941d2f308997e2451 (HEAD -> master, origin/master, origin/HEAD)
Author: Leon Weber <leonweber@users.noreply.github.com>
Date:   Wed Jan 22 11:02:41 2020 +0100

    Add instructions for training HUNER

    addresses https://github.com/hu-ner/huner/issues/13

commit 61766cd41e8db9d14eba6b0fa18573a074362986
Author: Leon Weber <leonweber@posteo.de>
Date:   Wed Jan 22 10:57:26 2020 +0100

    Add training scripts, addresses https://github.com/hu-ner/huner/issues/13

commit e1922817b9212617650317a5dad8fb126fbdafea
Merge: d419990 1628fca
Author: Leon Weber <leonweber@posteo.de>
Date:   Wed Jan 22 09:12:29 2020 +0100

    Merge branch 'master' of github.com:hu-ner/huner
```

Can you please provide the output of `git log` and the exact command that is failing for you?

**Comment by Eulring** [comment]
Thanks, @leonweber, I think you fixed this issue.
