### ISSUE TITLE
Multiple Entity Types Predicted per Mention

### ISSUE THREAD

**Issue by nakumgaurav** [hu-ner/huner#21]
Hi, it seems that some mentions are being predicted as belonging to multiple entity types:

![image](https://user-images.githubusercontent.com/22325652/78275777-ea365f80-74c6-11ea-8065-62991cc533cf.png)

I am assuming this happens since HUNER trains a separate model for each entity type. Is there a way to get the confidence scores of the predictions for each entity type, so as to select one out of the many categories? Thanks!

**Comment by leonweber** [comment]
Hey @nakumgaurav thanks for reporting this. I have added confidence estimation based on http://www.aclweb.org/anthology/N04-4028 here: https://github.com/hu-ner/huner/tree/confidence 

If you run client.py with --output_confidence you should receive the confidence per entity next to the corresponding B- tag. Does that resolve your issue?

**Comment by nakumgaurav** [comment]
Hi @leonweber , thanks a lot for the enhancement. On running the confidence branch, I get:

```
master: Pulling from huner/huner
Digest: sha256:58d71ec09e4f64db8b498dcc25d5e285d1146733746710049ce9bc18dd53d5c6
Status: Image is up to date for huner/huner:master
docker.io/huner/huner:master
Compiling...
 * Serving Flask app "tagger" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2020-04-07 09:21:50,899] ERROR in app: Exception on /tag [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tagger.py", line 59, in tag
    tokenized_sentences = [tokenize(s) for s in sentences]
  File "tagger.py", line 35, in tokenize
    return tokenizer.parse(sentence).decode().split()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 101: ordinal not in range(128)
```

The corresponding line in my text file is:
`The global market for adipic acid, an important aliphatic dicarboxylic acid, is estimated to reach £8 billion by 2022.`
where the 101th character is "£".
It seems that the scripts on `huner/huner:master` are not able to handle 'utf-8' characters, because if I use `huner/huner:latest`, it runs (but it doesn't have the confidence predictions). Could you please look into this?

**Comment by leonweber** [comment]
Can you please check whether https://github.com/hu-ner/huner/commit/79f3825cc7bae03ac8179d480ce520fdc4836e1a fixes this for you?

**Comment by nakumgaurav** [comment]
Hi @leonweber , I had tried the fix you suggested but for some reason, it only works for Python 3. Here is what I did to get it working:

1. Updated the scripts in huner to be Python 3 compatible - mostly print statements and using pickle instead of cPickle in model.py
2. Updated the huner/huner:master image by adding a few missing packages - Theano, Flask, joblib for Python3
3. In client.py:
`with open(args.input, "r", encoding='utf-8')`
If this doesn't work, [79f3825](https://github.com/hu-ner/huner/commit/79f3825cc7bae03ac8179d480ce520fdc4836e1a) could be tried, though I eventually didn't use it.
4. In tagger.py, the Flask app was restarting for some reason:  https://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat
To fix this, in tagger.py I changed the values of the parameters to app.run():
```
if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True, use_reloader=False)
```

Shall I issue a pull request for all the changes, or would you update the scripts to reflect the changes?

**Comment by leonweber** [comment]
Did you try using python3 for the client but python2 for everything else? I just realized that this is the setting I'm working with all the time.

**Comment by nakumgaurav** [comment]
I always used python3 for client, so I guess I must have tried that combination. In any case, wouldn't it be a good idea to update the entire pipeline with python 3?

**Comment by leonweber** [comment]
Hey @nakumgaurav, sorry for the delay in replying.
Unfortunately, we don't have the resources to convert everything into python3 at the moment. You would be more than welcome to submit an PR. Alternatively, there will be a better solution in the coming months, as we are currently working on integrating HUNER into [flair](https://github.com/flairNLP/flair)
