### ISSUE TITLE
'Model' object has no attribute 'id_to_word'

### ISSUE THREAD

**Issue by AndreasSaka** [hu-ner/huner#25]
Python 3
Environment: Google Colab
Command: !python /content/huner/train.py "/content/huner/models/gene_all" --train "/content/huner/data/TRAIN.txt" --dev "/content/huner/data/DEV.txt" --test "/content/huner/data/TEST.txt"

Traceback (most recent call last):
  File "/content/huner/train.py", line 139, in <module>
    f_train, f_eval = model.build(**parameters)
  File "/content/huner/model.py", line 131, in build
    n_words = len(self.id_to_word)
AttributeError: 'Model' object has no attribute 'id_to_word'

Any ideas, tips? My goal is to fine-tune the huner on my dataset (conll2003 format, with three columns Word: Pos: Tag)

**Comment by leonweber** [comment]
Hey @AndreasSaka, thanks for reporting this issue. I will look into it soon.

**Comment by leonweber** [comment]
The issue might be that train.py has be called with --model_path and --reload 1. Could you try using the following command:

```bash
python train.py --train "/content/huner/data/TRAIN.txt" --dev "/content/huner/data/DEV.txt" --test "/content/huner/data/TEST.txt" -s iob --dropout 0.3 --word_dim 200 --lr_method sgd-lr_.005 --model_path  "/content/huner/models/gene_all" --reload 1
```

**Comment by AndreasSaka** [comment]
@leonweber that works thanks a bunch!

**Comment by leonweber** [comment]
Thanks for reporting back!
