### ISSUE TITLE
Local version？

### ISSUE THREAD

**Issue by YaoXinZhi** [hu-ner/huner#26]
I want to know if HUNER provides a usable local version, because Docker configuration is very troublesome

**Comment by yetinam** [comment]
Hey,
indeed, we developed a new version of HUNER, that does not require docker and also shows even better NER performance. Please have a look at https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR.md . I hope this suits your needs.

**Comment by YaoXinZhi** [comment]
Thank you for your quick reply, I will try the new version of HUNER, it looks very “EASY-TO-USE” ！
