### ISSUE TITLE
mix up with metrics on readme and in HUNER paper?

### ISSUE THREAD

**Issue by SonjaAits** [hu-ner/huner#30]
Hi,
The table in the readme (https://github.com/hu-ner/huner#readme) lists evaluation results for the HUNER models on the HUNER test sets. As far as I can see the values in this readme table do not match the evaluation results in table 3 in the HUNER paper (https://doi.org/10.1093/bioinformatics/btz528) and only the values for the chemical model and disease model match table 4 in the paper. Also, table 4 presents results without fine-tuning and I assume the models in this repo were fine-tuned.

Was there some kind of mix up with the tables? Which is correct and is the evaluation code or a detailed evaluation description available?

Thank you

**Comment by yetinam** [comment]
Hi @SonjaAits ,

thank you for spotting this. Indeed, there has been a mix-up. The numbers in the paper are correct. I'll update the numbers in the README accordingly. Regarding the question of fine-tuning, the models in this repo are not fine-tuned. With fine-tuned we refer to models adapted to a specific corpus. The models in this repository are aimed at BioNER in general without adaptation to a specific corpus and are therefore not fine-tuned.

Please also note that for practical usage we strongly recommend our follow-up project HunFlair.

**Comment by SonjaAits** [comment]
Thanks for taking care of this so quickly! HunFlair is indeed excellent.
