### ISSUE TITLE
KeyError: 'OPENNLP'

### ISSUE THREAD

**Issue by Mahmedturk** [hu-ner/huner#4]
Hi, I get the following error when i run script for ner.
How could this be fixed?
python3 $SCRIPT_DIR/biosemantics_to_conll.py biosemantics M,I,Y,D,B,C,F,R,G,MOA biosemantics_chemical.conll
Traceback (most recent call last):
  File "scripts/biosemantics_to_conll.py", line 16, in <module>
    opennlp_path = os.environ['OPENNLP']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'OPENNLP'

**Comment by yetinam** [comment]
Hi, thanks for bringing this to our attention! To fix please install opennlp as explained in the README for ner_scripts and prefix your command with `OPENNLP=path/to/opennlp`.
Let me know if you encounter further problems.

**Comment by Mahmedturk** [comment]
HI I have fixed the above error,
