### ISSUE TITLE
Error in NER scripts

### ISSUE THREAD

**Issue by Mahmedturk** [hu-ner/huner#5]
HI, 

I get the below error while converting.  Where are the converted files being saved?

File "scripts/biosemantics_to_conll.py", line 68, in <module>
    with open(args.output, 'w') as f_out:
PermissionError: [Errno 13] Permission denied: '/biosemantics.conll'

**Comment by yetinam** [comment]
Hey,

thank you for reporting the issue. The output of "biosemantics_to_conll.py" is saved to the given output path from the command line. The arguments for the script are `input_file types output`. Could you paste the full command you are running to help us reproduce the issue?

**Comment by yetinam** [comment]
Closed due to inactivity
